### ISSUE TITLE
How to show line numbers

### ISSUE THREAD

**Issue by chinchang** [11ty/eleventy-plugin-syntaxhighlight#10]
How can I show line numbers in the syntax highlighting?

**Comment by seanomlor** [comment]
I'd love to use line numbers as well, any word on this? Let me know if I can help in any way.

**Comment by viljamis** [comment]
Wondering the same thing. Is there some way to utilize https://prismjs.com/plugins/line-numbers/ currently?

**Comment by joshbuchea** [comment]
I'm working on an eleventy based starter and I was able to get line numbers working with these two steps:

1. Enable `alwaysWrapLineHighlights` in the [eleventy syntax highlighting plugin options](https://www.11ty.dev/docs/plugins/syntaxhighlight/#options)
2. Add CSS

## Step 1

```js
// .eleventy.js
// ...
eleventyConfig.addPlugin(pluginSyntaxHighlight, {
  alwaysWrapLineHighlights: true,
});
```

## Step 2

```css
/* styles.css */
pre {
  counter-reset: lineNumber;
}
code .highlight-line:before {
  -webkit-user-select: none;
  border-right: 1px solid #404040;
  color: #858585;
  content: counter(lineNumber);
  counter-increment: lineNumber;
  display: inline-block;
  font-variant-numeric: tabular-nums;
  margin-right: 1.2em;
  padding-right: 1.2em;
  text-align: right;
  width: 2.4em;
}
```

## Screenshot

<img width="638" alt="Screen Shot 2020-10-06 at 6 18 11 PM" src="https://user-images.githubusercontent.com/1474361/95276563-5ee4b080-0800-11eb-963d-0fa5b86b543f.png">

Your mileage may vary, remove and styles you don't need. Hope this helps someone! ✌️
