### ISSUE TITLE
Diff Highlights

### ISSUE THREAD

**Issue by peterjcaulfield** [11ty/eleventy-plugin-syntaxhighlight#46]
The eleventy docs site for this plugin includes the following css snippets:

```css
.highlight-line-add {
  background-color: #45844b;
}
.highlight-line-remove {
  background-color: #902f2f;
}
```

Is diff highlighting supported? If so, what is the syntax? I tried:

\```language-diff-typescript
\-  const foo = 'test';
\+  const bar = 'test';
\```

and the highlight classes are not applied 🤔
